---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve-minio
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: 5080

---
# create statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  namespace: openobserve-minio
  labels:
    name: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      name: openobserve
      app: openobserve
  template:
    metadata:
      labels:
        name: openobserve
        app: openobserve
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      # terminationGracePeriodSeconds: 0
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:v0.6.2
          env:
            - name: ZO_ROOT_USER_EMAIL
              value: root@example.com
            - name: ZO_ROOT_USER_PASSWORD
              value: Complexpass#123
            - name: ZO_DATA_DIR
              value: /data
            - name: ZO_LOCAL_MODE
              value: "true"
            - name: ZO_LOCAL_MODE_STORAGE
              value: s3
            - name: ZO_S3_SERVER_URL
              value: http://minio-service.openobserve-minio.svc.cluster.local:9000
            - name: ZO_S3_ACCESS_KEY
              value: openobservekey
            - name: ZO_S3_SECRET_KEY
              value: openobservesecret
            - name: ZO_S3_BUCKET_NAME
              value: openobservebucket
            - name: ZO_S3_REGION_NAME
              value: "us-west-1"
          # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 4096m
              memory: 2048Mi
            requests:
              cpu: 256m
              memory: 50Mi
          ports:
            - containerPort: 5080
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        # storageClassName: default
        # NOTE: You can increase the storage size
        resources:
          requests:
            storage: 10Gi
